### ISSUE TITLE
Support namespace: '*' for Alert

### ISSUE THREAD

**Issue by arash-bizcover** [fluxcd/notification-controller#288] opened 2021-11-19 07:24 UTC
Same as selecting all names by putting `*`, namespace could be set the same.
**Currently avoiding to set namespace, don't support this behaviour. It seems it only includes flux-system.**

This way we can get all Alerts without statically/manually mentioning different namespaces for different clusters.

```diff
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
-    - kind: GitRepository
-      name: '*'
-      namespace: "flux-system"
-    - kind: Kustomization
-      namespace: "flux-system"
-      name: '*'
-    - kind: Kustomization
-      namespace: "ops"
-      name: '*'
-    - kind: HelmRelease
-      name: '*'
-      namespace: "flux-system"
-    - kind: HelmRelease
-      name: '*'
-      namespace: "ops"
-    - kind: HelmRelease
-      name: '*'
-      namespace: "dev-au"
-    - kind: HelmRelease
-      name: '*'
-      namespace: "dev2-au"
-    - kind: HelmRelease
-      name: '*'
-      namespace: "sit-au"
-    - kind: HelmRelease
-      name: '*'
-      namespace: "uat-au"
-    - kind: HelmRelease
-      name: '*'
-      namespace: "prod-au"
-    - kind: HelmRelease
-      name: '*'
-      namespace: "prod-us"
+    - kind: HelmRelease
+      name: '*'
+      namespace: "*"
+    - kind: Kustomization
+      name: '*'
+      namespace: "*"
+    - kind: GitRepository
+      name: '*'
+      namespace: "flux-system"
```

**Comment by stefanprodan** [comment] 2021-11-19 07:35
Duplicate of: #71

**Closed by stefanprodan** 2021-11-19 07:35 UTC
