### ISSUE TITLE
HelmRelease errors spam slack

### ISSUE THREAD

**Issue by nomeelnoj** [fluxcd/notification-controller#158] opened 2021-03-16 03:30 UTC
In setting up an alert to send to slack for `HelmRelease` objects at `error` level, it sends a ton of messages.  Here is a simple HelmRelease I applied, with an alert defined for `error`:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: broken-test
  namespace: default
spec:
  chart:
    spec:
      chart: charts/mychart
      sourceRef:
        kind: GitRepository
        name: gitops
        namespace: flux-system
  interval: 10m0s
  values:
    nothing: noone
```
This chart has a required value, so I knew this would trigger an error.  However, slack sent 22 messages within 3 seconds or so, all nearly identical.  We got 11 identical notifications for `Helm install failed` and 11 identical notifications for `reconciliation failed`.

Would it be possible to either thread these messages, or have a setting to limit number of messages within a given time frame? I could image something like this on the AlertSpec:

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: myalert
  namespace: flux-sustem
spec:
  thread: true # For each alert, thread additional messages for the same object type/name
  notifyWindow: 
    numMessages: 1
    timeDelay: 10m0s # Allow only one notification per object per error within the given time frame
```

**Comment by phillebaba** [comment] 2021-03-16 10:02
Notification controller does not determine how many messages to send, it only relays the events it receives from Helm controller. Currently NC does not keep any state of the amount of events sent. My guess is that the reason events are spammed is due to HC retrying to reconcile immediately. I will have to recreate this issue first to determine if the issue is in NC or HC.

**Comment by stefanprodan** [comment] 2021-03-16 10:08
@phillebaba all controllers use controller-runtime retry with backoff when a reconciliation fails. I think we could address this issue by using a rate limit solution like https://github.com/sethvargo/go-limiter. We could create a middleware that extract the message and the involved object from the request body, does a checksum used as the rate limiter key and returns StatusTooManyRequests if the checksum matches a previous received event, example here https://github.com/sethvargo/go-limiter/blob/main/httplimit/middleware.go

**Comment by phillebaba** [comment] 2021-03-16 10:31
Sounds like a good idea, it would resolve any future issue with bugs or unintended spamming. I will assign this to me and implement a rate limiter. What is the most reasonable way to configure it, in the Alert as suggested by @nomeelnoj or in the provider. Adding rate limits in the alert would allow for fine grained control but would require users to add it to all their alerts. While the provider would apply to all alerts but would allow for a single configuration point.

**Comment by nomeelnoj** [comment] 2021-03-17 12:41
This might be unrelated and impossible with the current implementation, but if the middleware will become "event aware", is there anyway to send a resolution event if the alert is resolved? For example, if the NC is set up at the same time as the image repos but the ECR creds have not been created yet, the NC will fire a bunch of alerts until the user creates those creds the first time. Would be really cool if once those resources are no longer causing issue that the slack message could be rewritten as green, letting the human operator know the issue is resolved, similar to the way Prometheus does.

**Comment by phillebaba** [comment] 2021-03-17 13:05
That may be a bit more complicated as the rate limiting will be done in memory. So deleting the NC pod will cause the rate limit to reset. I understand your point, and it would work similar to how alert manager works today. I don't really see how we would implement this without some sort of persistence of the alerts previously sent.

**Closed** 2021-04-01 09:57 UTC
Labels: area/alerting, enhancement
